services:
  - type: web
    name: victorryan
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - package.json
