services:
  - type: web
    name: victorryan
    env: node
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - package.json
        - package-lock.json
        - start.js
