services:
  - type: web
    name: card-game
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
